In [2]:
import pandas as pd

In [7]:
df = pd.read_csv("../data/raw_data.csv")

df

,CustomerID,Name,DateOfBirth,Gender,Email,TransactionID,TransactionDate,Product,Amount,City
0,101,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025/01/15,Laptop,55000,Hyderabad
1,102,Anita Sharma,1995-08-22,Female,anita@gmail.com,T002,15-01-2025,Mobile,25000,Bangalore
2,103,John Doe,NaN,Male,john@gmail.com,T003,2025-01-16,Tablet,18000,Chennai
3,104,Sneha Reddy,2001-03-10,Female,sneha@gmail.com,T004,2025-01-17,Laptop,54000,Hyderabad
4,105,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025/01/15,Laptop,55000,Hyderabad
5,106,Aman Gupta,1990-12-01,Male,NaN,T005,2025-01-18,Headphones,2000,Delhi
6,107,Priya Singh,1997-11-25,Female,priya@gmail.com,T006,2025-01-19,Mobile,24000,Mumbai
7,108,Karan Mehta,2003-06-14,Male,karan@gmail.com,T007,2025-01-20,Laptop,60000,Bangalore

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       8 non-null      int64
 1   Name             8 non-null      object
 2   DateOfBirth      7 non-null      object
 3   Gender           8 non-null      object
 4   Email            7 non-null      object
 5   TransactionID    8 non-null      object
 6   TransactionDate  8 non-null      object
 7   Product          8 non-null      object
 8   Amount           8 non-null      int64
 9   City             8 non-null      object
dtypes: int64(2), object(8)
memory usage: 768.0+ bytes

In [9]:
df.describe(include="all")

,CustomerID,Name,DateOfBirth,Gender,Email,TransactionID,TransactionDate,Product,Amount,City
count,8.00000,8,7,8,7,8,8,8,8.000000,8
unique,NaN,7,6,2,6,7,7,4,NaN,5
top,NaN,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025/01/15,Laptop,NaN,Hyderabad
freq,NaN,2,2,5,2,2,2,4,NaN,3
mean,104.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36625.000000,NaN
std,2.44949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21921.532141,NaN
min,101.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.000000,NaN
25%,102.75000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22500.000000,NaN
50%,104.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39500.000000,NaN
75%,106.25000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55000.000000,NaN
max,108.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60000.000000,NaN

In [10]:
df.isnull().sum()

CustomerID         0
Name               0
DateOfBirth        1
Gender             0
Email              1
TransactionID      0
TransactionDate    0
Product            0
Amount             0
City               0
dtype: int64

In [11]:
df = df.drop_duplicates()

df

,CustomerID,Name,DateOfBirth,Gender,Email,TransactionID,TransactionDate,Product,Amount,City
0,101,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025/01/15,Laptop,55000,Hyderabad
1,102,Anita Sharma,1995-08-22,Female,anita@gmail.com,T002,15-01-2025,Mobile,25000,Bangalore
2,103,John Doe,NaN,Male,john@gmail.com,T003,2025-01-16,Tablet,18000,Chennai
3,104,Sneha Reddy,2001-03-10,Female,sneha@gmail.com,T004,2025-01-17,Laptop,54000,Hyderabad
4,105,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025/01/15,Laptop,55000,Hyderabad
5,106,Aman Gupta,1990-12-01,Male,NaN,T005,2025-01-18,Headphones,2000,Delhi
6,107,Priya Singh,1997-11-25,Female,priya@gmail.com,T006,2025-01-19,Mobile,24000,Mumbai
7,108,Karan Mehta,2003-06-14,Male,karan@gmail.com,T007,2025-01-20,Laptop,60000,Bangalore

In [12]:

df["Email"] = df["Email"].fillna("Not Available")

df = df.dropna(subset=["DateOfBirth"])

df

,CustomerID,Name,DateOfBirth,Gender,Email,TransactionID,TransactionDate,Product,Amount,City
0,101,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025/01/15,Laptop,55000,Hyderabad
1,102,Anita Sharma,1995-08-22,Female,anita@gmail.com,T002,15-01-2025,Mobile,25000,Bangalore
3,104,Sneha Reddy,2001-03-10,Female,sneha@gmail.com,T004,2025-01-17,Laptop,54000,Hyderabad
4,105,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025/01/15,Laptop,55000,Hyderabad
5,106,Aman Gupta,1990-12-01,Male,Not Available,T005,2025-01-18,Headphones,2000,Delhi
6,107,Priya Singh,1997-11-25,Female,priya@gmail.com,T006,2025-01-19,Mobile,24000,Mumbai
7,108,Karan Mehta,2003-06-14,Male,karan@gmail.com,T007,2025-01-20,Laptop,60000,Bangalore

In [13]:
df["TransactionDate"] = pd.to_datetime(
    df["TransactionDate"],
    errors="coerce",
    dayfirst=True
)

df["DateOfBirth"] = pd.to_datetime(df["DateOfBirth"])

df

C:\Users\Shravya\AppData\Local\Temp\ipykernel_6484\818704939.py:1: UserWarning: Parsing dates in %Y/%m/%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["TransactionDate"] = pd.to_datetime(
C:\Users\Shravya\AppData\Local\Temp\ipykernel_6484\818704939.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["TransactionDate"] = pd.to_datetime(
C:\Users\Shravya\AppData\Local\Temp\ipykernel_6484\818704939.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["DateOfBirth"] = pd.to_datetime(df["DateOfBirth"])

,CustomerID,Name,DateOfBirth,Gender,Email,TransactionID,TransactionDate,Product,Amount,City
0,101,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025-01-15,Laptop,55000,Hyderabad
1,102,Anita Sharma,1995-08-22,Female,anita@gmail.com,T002,NaT,Mobile,25000,Bangalore
3,104,Sneha Reddy,2001-03-10,Female,sneha@gmail.com,T004,NaT,Laptop,54000,Hyderabad
4,105,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025-01-15,Laptop,55000,Hyderabad
5,106,Aman Gupta,1990-12-01,Male,Not Available,T005,NaT,Headphones,2000,Delhi
6,107,Priya Singh,1997-11-25,Female,priya@gmail.com,T006,NaT,Mobile,24000,Mumbai
7,108,Karan Mehta,2003-06-14,Male,karan@gmail.com,T007,NaT,Laptop,60000,Bangalore

In [14]:
today = pd.Timestamp("today")

df["CustomerAge"] = (
    (today - df["DateOfBirth"]).dt.days // 365
)

df

C:\Users\Shravya\AppData\Local\Temp\ipykernel_6484\4177741175.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["CustomerAge"] = (

,CustomerID,Name,DateOfBirth,Gender,Email,TransactionID,TransactionDate,Product,Amount,City,CustomerAge
0,101,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025-01-15,Laptop,55000,Hyderabad,27
1,102,Anita Sharma,1995-08-22,Female,anita@gmail.com,T002,NaT,Mobile,25000,Bangalore,30
3,104,Sneha Reddy,2001-03-10,Female,sneha@gmail.com,T004,NaT,Laptop,54000,Hyderabad,24
4,105,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025-01-15,Laptop,55000,Hyderabad,27
5,106,Aman Gupta,1990-12-01,Male,Not Available,T005,NaT,Headphones,2000,Delhi,35
6,107,Priya Singh,1997-11-25,Female,priya@gmail.com,T006,NaT,Mobile,24000,Mumbai,28
7,108,Karan Mehta,2003-06-14,Male,karan@gmail.com,T007,NaT,Laptop,60000,Bangalore,22

In [15]:
def product_category(p):
    if p in ["Laptop", "Mobile", "Tablet"]:
        return "Electronics"
    else:
        return "Accessories"

df["ProductCategory"] = df["Product"].apply(product_category)

df

C:\Users\Shravya\AppData\Local\Temp\ipykernel_6484\887522991.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ProductCategory"] = df["Product"].apply(product_category)

,CustomerID,Name,DateOfBirth,Gender,Email,TransactionID,TransactionDate,Product,Amount,City,CustomerAge,ProductCategory
0,101,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025-01-15,Laptop,55000,Hyderabad,27,Electronics
1,102,Anita Sharma,1995-08-22,Female,anita@gmail.com,T002,NaT,Mobile,25000,Bangalore,30,Electronics
3,104,Sneha Reddy,2001-03-10,Female,sneha@gmail.com,T004,NaT,Laptop,54000,Hyderabad,24,Electronics
4,105,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025-01-15,Laptop,55000,Hyderabad,27,Electronics
5,106,Aman Gupta,1990-12-01,Male,Not Available,T005,NaT,Headphones,2000,Delhi,35,Accessories
6,107,Priya Singh,1997-11-25,Female,priya@gmail.com,T006,NaT,Mobile,24000,Mumbai,28,Electronics
7,108,Karan Mehta,2003-06-14,Male,karan@gmail.com,T007,NaT,Laptop,60000,Bangalore,22,Electronics

In [16]:
df

,CustomerID,Name,DateOfBirth,Gender,Email,TransactionID,TransactionDate,Product,Amount,City,CustomerAge,ProductCategory
0,101,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025-01-15,Laptop,55000,Hyderabad,27,Electronics
1,102,Anita Sharma,1995-08-22,Female,anita@gmail.com,T002,NaT,Mobile,25000,Bangalore,30,Electronics
3,104,Sneha Reddy,2001-03-10,Female,sneha@gmail.com,T004,NaT,Laptop,54000,Hyderabad,24,Electronics
4,105,Ravi Kumar,1998-05-12,Male,ravi@gmail.com,T001,2025-01-15,Laptop,55000,Hyderabad,27,Electronics
5,106,Aman Gupta,1990-12-01,Male,Not Available,T005,NaT,Headphones,2000,Delhi,35,Accessories
6,107,Priya Singh,1997-11-25,Female,priya@gmail.com,T006,NaT,Mobile,24000,Mumbai,28,Electronics
7,108,Karan Mehta,2003-06-14,Male,karan@gmail.com,T007,NaT,Laptop,60000,Bangalore,22,Electronics

In [17]:
df.to_csv("../data/cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!